### ISSUE TITLE
Officially supporting this datasource?

### ISSUE THREAD

**Issue by ravage84** [ptica/Oracle#18]
Hi @ptica ,

Due to a project demand we need to query and insert into an ORACLE DB.
After searching for a working CakePHP 2.x datasource for ORACLE, I came across yours (besides some others).

I could get it to work (querying), but I think the datasource is a bit rough on the edges and could need some more love.

I saw you updated the class recently, but I wanted check with you, whether you actually want to (further) suport this plugin/repo.

If so, I will contribute to your repo. Otherwise I will fork yours and work on my own.
I personally would prefer the first, but I do not want to force you into offically supporting something like this, especially since there is CakePHP 3.x out.

Thank you for your work.

**Comment by ptica** [comment]
Hi,
this came out from a urgent need to port an existing app to Oracle db,
having near to zero experience with Oracle I've done some minimal changes to get it sort of working in my use case.

I've tagged current version so I can refer to it, thus don't be afraid to push any code you find needed.

I have a vague notion that the db tests from cake test suite do not pass :)

**Comment by ravage84** [comment]
Hey, I see you had the same situation as I'm now it :smirk_cat: 

I have no experience with ORACLE, too.

I forked your repo and will work on my repo first.
Also I will create various issues to get us (and anybody interested) a TODO list to work on.

But the most important stuff is to get the utmost necessary functions to work without errosr or notices.
